name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #  Update python version matrix compatible with your project
        python: ["3.13"]

    steps:
      #  This will remove unnecessary files to free up space. This has done because some package needs more space to install. e.g.) torch
      - name: Clean up space for action
        run: rm -rf /opt/hostedtoolcache

      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
      #  Install project dependencies with pytest and run tests
      - name: Install dependencies
        run: |
          uv sync
          uv pip list

      #  `-rs` flag is used to debug for the test failure
      - name: Run test
        run: uv run python -m pytest tests/ -v